#!/usr/bin/env ash

if [ $# -gt 0 ]; then
  exec exec /usr/local/bin/php /var/www/html/artisan queue:work "$@"
else
  exec /usr/local/bin/php /var/www/html/artisan queue:work --timeout=3600 --tries=3 --no-interaction
fi
